(define (make-account balance password)
  (define login-error-count 0)
  (define (withdraw amount)
    (set! login-error-count 0)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! login-error-count 0)
    (set! balance (+ balance amount))
    balance)
  (define (login-error amount)
    (set! login-error-count (+ 1 login-error-count))
    (if (< login-error-count 7)
	"Incorrect password"
	(call-the-cops)))
  (define (call-the-cops)
    "110 -- calling the cops")
  (define (dispatch pw m)
    (if (eq? pw password)
	(cond ((eq? m 'withdraw) withdraw)
	      ((eq? m 'deposit) deposit)
	      (else (error "Unknown request -- MAKE-ACCOUNT"
			   m)))
	login-error))
  dispatch)
